### ISSUE TITLE
想把这个系列写的更面向newbie.

### ISSUE THREAD

**Issue by jerryling315** [lao605/shadowsocks_analysis#2]
SS是一个很优秀的Python Socket源代码案例. 不仅很Pythonic而且短小精悍. 特别是最近之后想对SS源代码了解/学习的人会变多. 之前在G+上也看到讨论在说接下来开源SS没有人维护/讨论. 靠SS-R闭源修炼3-6个月是不是不太好.

想项这个repo贡献一点分析

**Comment by lao605** [comment]
其实我也注意到了最近很多人fork我这个repo，将它做的更加完善也在我的日程里面，因为其实这里的analysis只做了个大概，而我也计划进行相关的开发。所以非常欢迎你的贡献。而关于具体怎么完善这个repo，我还需要点时间去做下调研。

**Comment by jerryling315** [comment]
Sure√

**Comment by jerryling315** [comment]
建议开一个Gitter频道方便交流, G+太不方便而且不是圈子内的

**Comment by lao605** [comment]
Thanks. Gitter is a really convenient way to chat.
